### PR TITLE
New feature: Import Spansh Road to Riches CSV file

### LINKED ISSUE #22: create routes for Fleet Carriers
would it be possible to modify this plugin to add routes that don't use neutrons so that they can be used for fleet carriers? possibly a FC checkbox that will just generate a standard route of max jump distance 500LY per hop.

### PR DESCRIPTION
**Pull request by Stumpii**
1. Import Spansh Road to Riches CSV file and subsequently show those bodies that are worth scanning in the system by name and type.
2. Import Spansh Fleet Carrier CSV file and indicate when it is time to refuel.
3. Provide a route export for Trade Computer Extension Mk II which has its own import format (CSV).
4. For the above, modified the import and export functions to allow for future formats.

### CODE REVIEW

**Comment by rouben** [comment]
I tested this fork of the plugin and can attest that it works quite nicely. The UI tends to resize spontaneously between system jumps, but when the UI is set to transparent mode it's not that big of a deal. Also I am not sure if this is caused by this plugin specifically, or perhaps other plugins I have, or an interaction of one or more plugins. Seemed to start happening once I switched from the original build of this plugin to this fork, so I am inclined to think it's this fork...

**Comment by Stumpii** [comment]
> I tested this fork of the plugin and can attest that it works quite nicely. The UI tends to resize spontaneously between system jumps, but when the UI is set to transparent mode it's not that big of a deal. Also I am not sure if this is caused by this plugin specifically, or perhaps other plugins I have, or an interaction of one or more plugins. Seemed to start happening once I switched from the original build of this plugin to this fork, so I am inclined to think it's this fork...

The cause is the length of the system name.  If the system name is long, the window will increase in width. So I don't believe it is caused by the fork, but I can check by finding the longest system name I have come across and run the original and fork. I did split the button to two lines and change the layout of the planets to reduce the problem.

**Comment by BraINstinct0** [comment]
Unable to write a commit for this, but adding a 'cutting out too long system names' option would be a viable one.
Slicing the string at display will do it, I guess?

**Comment by CMDR-Kiel42** [comment]
I'll take a look at the pull request when I get home tonight.
As for the slicing, I don't think that's ideal as some systems have very similar names, and it could end up just being confusing.
I think a better solution would be wrapping the system name. I'll check it out tonight as well

**Comment by rouben** [comment]
I think as long as the full system name is copied to the clipboard for easy galaxy map pasting, and there is a way to re-copy the full system name to the clipboard manually (e.g. by clicking it on the EDMC interface), truncating should be OK.

If you do choose truncation, please show a visual indicator like an ellipsis to make it clear the name is truncated.

**Comment by CMDR-Kiel42** [comment]
Looks good to me, I'll release a new version in a few days.

> If you do choose truncation, please show a visual indicator like an ellipsis to make it clear the name is truncated.

I'll tinker with both truncation and wrapping and see which one I like the most (but it's most probably gonna be truncation).

**Pull request merged**
